### ISSUE TITLE
Unexpected return value of Cldr.Unit.to_string

### ISSUE THREAD

**Issue by LostKobrakai** [kipcole9/cldr_units#1]
Using v0.4.2 I get the following unexpected function call result:

```elixir
> Cldr.Unit.to_string(size, map_sizable_unit_to_cldr_unit(unit), style: :short, locale: "de_DE")
{:ok, {:error, {Cldr.UnknownLocaleError, "The locale "de" is not known."}}}
```
This doesn't seem like a desirable way of reporting an error besides the fact that "de" should be known.

**Comment by LostKobrakai** [comment]
Probably because `pattern_for` does return error tuples, but `verify_unit()` does only check for boolean true.

**Comment by kipcole9** [comment]
Hmmmm.  I'm not seeing the error.  Anything else you can suggest to help me pin it down?
```elixir
iex> Cldr.Unit.to_string 1234, :gallon, format: :short, locale: "de_DE"
{:ok, "1 Tsd. Gallonen"}

iex> Cldr.Unit.to_string 1234, :gallon, format: :short, locale: "ro"   
{:error, {Cldr.UnknownLocaleError, "The locale \"ro\" is not known."}}
```

You have helped me (a) fix a messed up doctest and (b) identify a bug in `Cldr.validate_locale/1` for locale names like `en-XX` where `XX` is not a valid territory.

**Comment by kipcole9** [comment]
Ahhh, can reproduce - poor handling of invalid unit types (what you said above).  Fixing now.
