### ISSUE TITLE
Readme typo in a convert example

### ISSUE THREAD

**Issue by DamienFriot** [kipcole9/cldr_units#16]
Thanks for your library!

An example in the Readme has apparently a typo: MyApp.Cldr.Unit.convert MyApp.Cldr.Unit.new(:foot, 3), :meter
To make it work, I have to use new!

**Comment by kipcole9** [comment]
Thanks for the report. Fixed in master and I'll publish when I update for the feature request you have in issue #18.

The changelog entry is:

### Bug Fixes

* Fix readme example for `MyApp.Cldr.Unit.convert/2`.  Thanks to @DamienFF. Closes #16.

* Add missing `<backend>.convert!/2`
