### ISSUE TITLE
404 on doc link

### ISSUE THREAD

**Issue by hassan** [kipcole9/cldr_units#25]
Clicking the src (</>) link on this page https://hexdocs.pm/ex_cldr_units/Cldr.Unit.Conversion.html#convert/2
-> https://github.com/elixir-cldr/cldr_units/blob/v3.11.0/lib/cldr/unit/conversion.ex#L133 is 404

Other links on that page seem to have the same problem.

**Comment by kipcole9** [comment]
@hassan Thanks for the report and sorry for the inconvenience. I had neglected to tag the release - which I have now done.  The source links should now work correctly.

**Comment by hassan** [comment]
Fix confirmed, and thank you for all your work on this great library!
