### ISSUE TITLE
Documentation for adding new unit localizations

### ISSUE THREAD

**Issue by ribanez7** [kipcole9/cldr_units#34]
The only way I have found to make it work is not the one in the README, but this one:

```elixir
  unit_localization(:person, "ja", :long,
    nominative: %{
      one: "{0} 人",
      other: "{0} 人"
    },
    display_name: "人"
  )
```

Can you confirm that's correct? if so I can update it.

**Comment by kipcole9** [comment]
You are correct, the README.md needs updating (the [changelog entry for ex_cldr_units 3.5.0](https://hexdocs.pm/ex_cldr_units/changelog.html#enhancements-11) has the up-to-date information.

A PR would be very welcome.

**Comment by ribanez7** [comment]
Closing!
