### ISSUE TITLE
split_into_units breaks when input is SI prefix only

### ISSUE THREAD

**Issue by maltoe** [kipcole9/cldr_units#46]
Hello :wave: 

we're trying to use `validate_unit/1` to validate input strings to be valid units, and doing this on change of the form, so we're getting all interim values. Strings that only contain an SI prefix currently break in the parser:

```elixir
iex(1)> Cldr.Unit.validate_unit("centi")
** (MatchError) no match of right hand side value: []
    (ex_cldr_units 3.17.0) lib/cldr/unit/parser.ex:351: Cldr.Unit.Parser.split_into_units/1
    (ex_cldr_units 3.17.0) lib/cldr/unit/parser.ex:138: Cldr.Unit.Parser.parse_subunit/1
    (ex_cldr_units 3.17.0) lib/cldr/unit/parser.ex:117: Cldr.Unit.Parser.parse_subunits/1
    (ex_cldr_units 3.17.0) lib/cldr/unit/parser.ex:101: Cldr.Unit.Parser.parse_unit/1
    (ex_cldr_units 3.17.0) lib/cldr/unit.ex:2537: Cldr.Unit.return_parsed_unit/1
    iex:1: (file)
```

Best,
malte

**Comment by kipcole9** [comment]
@maltoe, thanks for the report. Given that `centi` (or other SI prefixes) aren't valid units, I'm not sure there is a solution to this issue that fits in the scope of `ex_cldr_units`.

What behaviour are you expecting?  Do you have some thoughts on what an API would look like?  Parse only prefixes perhaps?

(sorry for the slow response, I'm travelling the next few weeks which slows me down a bit).

**Comment by maltoe** [comment]
I'd expect it to return `{:error, {Cldr.UnknownUnitError, _}}` just like for normal non-existent units, I just don't want it to explode on me. Sorry if I was unclear in the original description.

**Comment by maltoe** [comment]
turned out a fairly simple fix ^^

**Comment by kipcole9** [comment]
My apologies, I misunderstood the issue. Of course it shouldn't raise an exception on a parse error - thank you very much indeed for the PR.  I'll work on this now. Sorry for the confusion (on my part).
