### ISSUE TITLE
Cldr.Unit.convert documentation

### ISSUE THREAD

**Issue by LostKobrakai** [kipcole9/cldr_units#5]
The documentation for `Cldr.Unit.convert` does show `convert(unit_1, unit_2)`, which should propably be `convert(unit, to_unit)` like in the linked documentation of `Cldr.Unit.Conversion`.

**Comment by kipcole9** [comment]
Good feedback, thank you.  I will fix it over the weekend.

**Comment by kipcole9** [comment]
Fixed and pubished v1.1.0 on hex.
