### ISSUE TITLE
API to get the value of a Cldr.Unit struct

### ISSUE THREAD

**Issue by LostKobrakai** [kipcole9/cldr_units#6]
I'm using Cldr.Unit not only because of it's formatting capabilities, but also as general purpose unit type within my system. So in some places it might be nice to have an API method for getting back the value of the struct as well.

**Comment by kipcole9** [comment]
@LostKobrakai Thanks as always for the constructive feedback.  And I've not forgotten our previous conversation and your request either.  I'll be able to make a proposal for this issue over the weekend.  Is that timing acceptable to you?

**Comment by LostKobrakai** [comment]
Sure I've simply gone with `stuct.value` for now.

**Comment by kipcole9** [comment]
Added `Cldr.Unit.value/1` and published in hex 1.1.0.
